### ISSUE TITLE
bug: failed to build common-meta-app after #7778

### ISSUE THREAD

**Issue by andylokandy** [datafuselabs/databend#7793]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main - 9e41e2501

### What's Wrong?

```
error[E0277]: the trait bound `DateTime<Utc>: Deserialize<'_>` is not satisfied
    --> src/meta/app/src/share/share.rs:384:20
     |
384  |     pub update_on: Option<DateTime<Utc>>,
     |                    ^^^^^^^^^^^^^^^^^^^^^ the trait `Deserialize<'_>` is not implemented for `DateTime<Utc>`
     |
     = help: the following other types implement trait `Deserialize<'de>`:
               <&'a Path as Deserialize<'de>>
               <&'a [u8] as Deserialize<'de>>
               <&'a bstr::bstr::BStr as Deserialize<'de>>
               <&'a str as Deserialize<'de>>
               <() as Deserialize<'de>>
               <(T0, T1) as Deserialize<'de>>
               <(T0, T1, T2) as Deserialize<'de>>
               <(T0, T1, T2, T3) as Deserialize<'de>>
             and 558 others
     = note: required for `std::option::Option<DateTime<Utc>>` to implement `Deserialize<'_>`
note: required by a bound in `next_value`
    --> /Users/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.144/src/de/mod.rs:1869:12
     |
1869 |         V: Deserialize<'de>,
     |            ^^^^^^^^^^^^^^^^ required by this bound in `next_value`
```

### How to Reproduce?

cargo test -p common-functions-v2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by andylokandy** [comment]
cc @PsiACE

**Comment by Xuanwo** [comment]
Have tried cargo clean?

**Comment by andylokandy** [comment]
@Xuanwo yes

**Comment by PsiACE** [comment]
I can reproduce the problem, but it looks odd if you run `cargo test` instead of `cargo test -p common-functions-v2` and everything works fine.
