### ISSUE TITLE
Build failed after upgrade clap from 3.0.0-beta.5 to 3.0.0-rc.0

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#3322]
**Summary**

Databend CLI will build failed after upgrade clap from 3.0.0-beta.5 to 3.0.0-rc.0

```rust
error[E0599]: no method named `about` found for struct `Arg` in the current scope
   --> cli/src/cmds/root.rs:110:22
    |
110 |                     .about("Sets the log-level for current settings")
    |                      ^^^^^ method not found in `Arg<'_>`
    |
    = help: items from traits can only be used if the trait is implemented and in scope
note: `command::Command` defines an item `about`, perhaps you need to implement it
   --> cli/src/cmds/command.rs:26:1
    |
26  | pub trait Command: DynClone + Send + Sync {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
